using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace NetCorePal.Extensions.CodeAnalysis.Snapshots;

/// <summary>
/// 代码流分析快照辅助类，提供快照的创建、代码生成和扫描功能
/// </summary>
public static class CodeFlowAnalysisSnapshotHelper
{
    /// <summary>
    /// 基于CodeFlowAnalysisResult构造CodeFlowAnalysisSnapshot实例
    /// </summary>
    /// <param name="analysisResult">分析结果</param>
    /// <param name="description">快照描述</param>
    /// <param name="version">快照版本号（可选，默认使用时间戳）</param>
    /// <returns>快照实例</returns>
    public static CodeFlowAnalysisSnapshot CreateSnapshot(
        CodeFlowAnalysisResult analysisResult, 
        string description, 
        string? version = null)
    {
        version ??= DateTime.Now.ToString("yyyyMMddHHmmss");
        
        var metadata = new SnapshotMetadata
        {
            Version = version,
            Timestamp = DateTime.Now,
            Description = description,
            Hash = ComputeHash(analysisResult),
            NodeCount = analysisResult.Nodes.Count,
            RelationshipCount = analysisResult.Relationships.Count
        };
        
        return new CodeFlowAnalysisSnapshot
        {
            Metadata = metadata,
            AnalysisResult = analysisResult
        };
    }
    
    /// <summary>
    /// 基于CodeFlowAnalysisSnapshot实例，生成C#快照类代码（类似EF Core迁移）
    /// </summary>
    /// <param name="snapshot">快照实例</param>
    /// <returns>C#代码字符串</returns>
    public static string GenerateSnapshotCode(CodeFlowAnalysisSnapshot snapshot)
    {
        return GenerateSnapshotCode(snapshot.AnalysisResult, snapshot.Metadata);
    }
    
    /// <summary>
    /// 基于分析结果和元数据，生成C#快照类代码
    /// </summary>
    /// <param name="analysisResult">分析结果</param>
    /// <param name="metadata">快照元数据</param>
    /// <returns>C#代码字符串</returns>
    public static string GenerateSnapshotCode(CodeFlowAnalysisResult analysisResult, SnapshotMetadata metadata)
    {
        var sb = new StringBuilder();
        
        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Snapshot created: {metadata.Timestamp:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// Description: {EscapeCSharpString(metadata.Description)}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis.Snapshots;");
        sb.AppendLine();
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        
        // Namespace
        sb.AppendLine("namespace CodeAnalysisSnapshots");
        sb.AppendLine("{");
        
        // Class declaration
        var className = $"Snapshot_{metadata.Version}";
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");
        
        // BuildSnapshot method
        sb.AppendLine("        public static CodeFlowAnalysisSnapshot BuildSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            var nodes = new List<Node>");
        sb.AppendLine("            {");
        
        // Generate nodes
        foreach (var node in analysisResult.Nodes)
        {
            sb.AppendLine("                new Node");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Id = \"{EscapeCSharpString(node.Id)}\",");
            sb.AppendLine($"                    Name = \"{EscapeCSharpString(node.Name)}\",");
            sb.AppendLine($"                    FullName = \"{EscapeCSharpString(node.FullName)}\",");
            sb.AppendLine($"                    Type = NodeType.{node.Type}");
            sb.AppendLine("                },");
        }
        
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            var relationships = new List<Relationship>");
        sb.AppendLine("            {");
        
        // Generate relationships (need to reference nodes from the list)
        var nodeDict = analysisResult.Nodes.Select((n, i) => new { n.Id, Index = i }).ToDictionary(x => x.Id, x => x.Index);
        
        foreach (var rel in analysisResult.Relationships)
        {
            var fromIndex = nodeDict.TryGetValue(rel.FromNode.Id, out var fi) ? fi : -1;
            var toIndex = nodeDict.TryGetValue(rel.ToNode.Id, out var ti) ? ti : -1;
            
            if (fromIndex >= 0 && toIndex >= 0)
            {
                sb.AppendLine($"                new Relationship(nodes[{fromIndex}], nodes[{toIndex}], RelationshipType.{rel.Type}),");
            }
        }
        
        sb.AppendLine("            };");
        sb.AppendLine();
        
        // Create and return snapshot
        sb.AppendLine("            return new CodeFlowAnalysisSnapshot");
        sb.AppendLine("            {");
        sb.AppendLine("                Metadata = new SnapshotMetadata");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Version = \"{metadata.Version}\",");
        sb.AppendLine($"                    Timestamp = DateTime.Parse(\"{metadata.Timestamp:yyyy-MM-dd HH:mm:ss}\"),");
        sb.AppendLine($"                    Description = \"{EscapeCSharpString(metadata.Description)}\",");
        sb.AppendLine($"                    Hash = \"{metadata.Hash}\",");
        sb.AppendLine($"                    NodeCount = {metadata.NodeCount},");
        sb.AppendLine($"                    RelationshipCount = {metadata.RelationshipCount}");
        sb.AppendLine("                },");
        sb.AppendLine("                AnalysisResult = new CodeFlowAnalysisResult");
        sb.AppendLine("                {");
        sb.AppendLine("                    Nodes = nodes,");
        sb.AppendLine("                    Relationships = relationships");
        sb.AppendLine("                }");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 从程序集中扫描获取CodeFlowAnalysisSnapshot实例列表
    /// </summary>
    /// <param name="assemblies">要扫描的程序集数组</param>
    /// <returns>快照实例列表</returns>
    public static List<CodeFlowAnalysisSnapshot> ScanSnapshotsFromAssemblies(params Assembly[] assemblies)
    {
        var snapshots = new List<CodeFlowAnalysisSnapshot>();
        
        foreach (var assembly in assemblies)
        {
            try
            {
                // 查找所有快照类（在CodeAnalysisSnapshots命名空间下，类名以Snapshot_开头）
                var snapshotTypes = assembly.GetTypes()
                    .Where(t => t.Namespace == "CodeAnalysisSnapshots" 
                             && t.Name.StartsWith("Snapshot_")
                             && t.IsClass 
                             && !t.IsAbstract)
                    .ToList();
                
                foreach (var type in snapshotTypes)
                {
                    // 查找BuildSnapshot静态方法
                    var buildMethod = type.GetMethod("BuildSnapshot", 
                        BindingFlags.Public | BindingFlags.Static);
                    
                    if (buildMethod != null 
                        && buildMethod.ReturnType == typeof(CodeFlowAnalysisSnapshot)
                        && buildMethod.GetParameters().Length == 0)
                    {
                        // 调用BuildSnapshot方法获取快照实例
                        var snapshot = buildMethod.Invoke(null, null) as CodeFlowAnalysisSnapshot;
                        if (snapshot != null)
                        {
                            snapshots.Add(snapshot);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // 记录错误但继续处理其他程序集
                Console.Error.WriteLine($"Error scanning assembly {assembly.FullName}: {ex.Message}");
            }
        }
        
        // 按版本号排序
        return snapshots.OrderBy(s => s.Metadata.Version).ToList();
    }
    
    /// <summary>
    /// 计算分析结果的哈希值
    /// </summary>
    private static string ComputeHash(CodeFlowAnalysisResult analysisResult)
    {
        var sb = new StringBuilder();
        foreach (var node in analysisResult.Nodes.OrderBy(n => n.Id))
        {
            sb.Append($"{node.Id}|{node.Name}|{node.Type}|");
        }
        foreach (var rel in analysisResult.Relationships.OrderBy(r => r.FromNode.Id).ThenBy(r => r.ToNode.Id))
        {
            sb.Append($"{rel.FromNode.Id}->{rel.ToNode.Id}|{rel.Type}|");
        }
        using var sha256 = SHA256.Create();
        var hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }
    
    /// <summary>
    /// 转义C#字符串
    /// </summary>
    private static string EscapeCSharpString(string input)
    {
        if (string.IsNullOrEmpty(input))
            return string.Empty;
            
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
