using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using NetCorePal.Extensions.CodeAnalysis.Attributes;

namespace NetCorePal.Extensions.CodeAnalysis.Snapshots;

/// <summary>
/// 代码流分析快照辅助类，提供快照的创建、代码生成和扫描功能
/// </summary>
public static class CodeFlowAnalysisSnapshotHelper
{
    /// <summary>
    /// 基于MetadataAttribute集合构造CodeFlowAnalysisSnapshot实例
    /// </summary>
    /// <param name="metadataAttributes">元数据特性集合</param>
    /// <param name="description">快照描述</param>
    /// <param name="version">快照版本号（可选，默认使用时间戳）</param>
    /// <returns>快照实例</returns>
    public static CodeFlowAnalysisSnapshot CreateSnapshot(
        List<MetadataAttribute> metadataAttributes, 
        string description, 
        string? version = null)
    {
        version ??= DateTime.Now.ToString("yyyyMMddHHmmss");
        
        // 从MetadataAttributes生成CodeFlowAnalysisResult用于计算统计信息
        var analysisResult = CodeFlowAnalysisHelper.GetResultFromMetadataAttributes(metadataAttributes);
        
        var metadata = new SnapshotMetadata
        {
            Version = version,
            Timestamp = DateTime.Now,
            Description = description,
            Hash = ComputeHash(analysisResult),
            NodeCount = analysisResult.Nodes.Count,
            RelationshipCount = analysisResult.Relationships.Count
        };
        
        return new RuntimeSnapshot(metadata, metadataAttributes);
    }
    
    /// <summary>
    /// 基于CodeFlowAnalysisSnapshot实例，生成C#快照类代码（继承自CodeFlowAnalysisSnapshot抽象基类）
    /// </summary>
    /// <param name="snapshot">快照实例</param>
    /// <param name="snapshotName">快照名称（可选，用于生成更具描述性的类名）</param>
    /// <returns>C#代码字符串</returns>
    public static string GenerateSnapshotCode(CodeFlowAnalysisSnapshot snapshot, string? snapshotName = null)
    {
        return GenerateSnapshotCode(snapshot.MetadataAttributes, snapshot.Metadata, snapshotName);
    }
    
    /// <summary>
    /// 基于MetadataAttribute集合和元数据，生成C#快照类代码（继承自CodeFlowAnalysisSnapshot抽象基类）
    /// </summary>
    /// <param name="metadataAttributes">元数据特性集合</param>
    /// <param name="metadata">快照元数据</param>
    /// <param name="snapshotName">快照名称（可选，用于生成更具描述性的类名）</param>
    /// <returns>C#代码字符串</returns>
    public static string GenerateSnapshotCode(List<MetadataAttribute> metadataAttributes, SnapshotMetadata metadata, string? snapshotName = null)
    {
        var sb = new StringBuilder();
        
        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Snapshot created: {metadata.Timestamp:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// Description: {EscapeCSharpString(metadata.Description)}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis.Attributes;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis.Snapshots;");
        sb.AppendLine();
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        
        // Namespace
        sb.AppendLine("namespace CodeAnalysisSnapshots");
        sb.AppendLine("{");
        
        // Class declaration - inherits from CodeFlowAnalysisSnapshot
        var className = GenerateClassName(metadata.Version, snapshotName);
        sb.AppendLine($"    public partial class {className} : CodeFlowAnalysisSnapshot");
        sb.AppendLine("    {");
        
        // Constructor to initialize metadata and attributes
        sb.AppendLine($"        public {className}()");
        sb.AppendLine("        {");
        
        // Generate MetadataAttributes list
        sb.AppendLine("            var attributes = new List<MetadataAttribute>");
        sb.AppendLine("            {");
        
        foreach (var attr in metadataAttributes)
        {
            sb.AppendLine($"                {GenerateMetadataAttributeCode(attr)},");
        }
        
        sb.AppendLine("            };");
        sb.AppendLine();
        
        // Initialize metadata and MetadataAttributes in constructor
        sb.AppendLine("            Metadata = new SnapshotMetadata");
        sb.AppendLine("            {");
        sb.AppendLine($"                Version = \"{metadata.Version}\",");
        sb.AppendLine($"                Timestamp = DateTime.Parse(\"{metadata.Timestamp:yyyy-MM-dd HH:mm:ss}\"),");
        sb.AppendLine($"                Description = \"{EscapeCSharpString(metadata.Description)}\",");
        sb.AppendLine($"                Hash = \"{metadata.Hash}\",");
        sb.AppendLine($"                NodeCount = {metadata.NodeCount},");
        sb.AppendLine($"                RelationshipCount = {metadata.RelationshipCount}");
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            MetadataAttributes = attributes;");
        sb.AppendLine("        }");
        
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    /// <summary>
    /// 生成MetadataAttribute的C#代码
    /// </summary>
    private static string GenerateMetadataAttributeCode(MetadataAttribute attr)
    {
        // 根据不同的MetadataAttribute类型生成相应的代码
        return attr switch
        {
            EntityMethodMetadataAttribute entityMethod => 
                $"new EntityMethodMetadataAttribute(\"{EscapeCSharpString(entityMethod.EntityType)}\", \"{EscapeCSharpString(entityMethod.MethodName)}\") {{ EmittedEvents = new[] {{ {string.Join(", ", entityMethod.EmittedEvents?.Select(e => $"\"{EscapeCSharpString(e)}\"") ?? Array.Empty<string>())} }}, CalledEntityMethods = new[] {{ {string.Join(", ", entityMethod.CalledEntityMethods?.Select(m => $"\"{EscapeCSharpString(m)}\"") ?? Array.Empty<string>())} }} }}",
            
            CommandHandlerEntityMethodMetadataAttribute cmdHandlerMethod =>
                $"new CommandHandlerEntityMethodMetadataAttribute(\"{EscapeCSharpString(cmdHandlerMethod.HandlerType)}\", \"{EscapeCSharpString(cmdHandlerMethod.EntityType)}\", \"{EscapeCSharpString(cmdHandlerMethod.EntityMethodName)}\")",
            
            EntityMetadataAttribute entity =>
                $"new EntityMetadataAttribute(\"{EscapeCSharpString(entity.EntityType)}\")",
            
            CommandMetadataAttribute command =>
                $"new CommandMetadataAttribute(\"{EscapeCSharpString(command.CommandType)}\")",
            
            CommandHandlerMetadataAttribute commandHandler =>
                $"new CommandHandlerMetadataAttribute(\"{EscapeCSharpString(commandHandler.HandlerType)}\", \"{EscapeCSharpString(commandHandler.CommandType)}\")",
            
            DomainEventMetadataAttribute domainEvent =>
                $"new DomainEventMetadataAttribute(\"{EscapeCSharpString(domainEvent.EventType)}\")",
            
            DomainEventHandlerMetadataAttribute domainEventHandler =>
                $"new DomainEventHandlerMetadataAttribute(\"{EscapeCSharpString(domainEventHandler.HandlerType)}\", \"{EscapeCSharpString(domainEventHandler.EventType)}\") {{ SendCommands = new[] {{ {string.Join(", ", domainEventHandler.SendCommands?.Select(c => $"\"{EscapeCSharpString(c)}\"") ?? Array.Empty<string>())} }} }}",
            
            IntegrationEventMetadataAttribute integrationEvent =>
                $"new IntegrationEventMetadataAttribute(\"{EscapeCSharpString(integrationEvent.EventType)}\")",
            
            IntegrationEventHandlerMetadataAttribute integrationEventHandler =>
                $"new IntegrationEventHandlerMetadataAttribute(\"{EscapeCSharpString(integrationEventHandler.HandlerType)}\", \"{EscapeCSharpString(integrationEventHandler.EventType)}\") {{ SendCommands = new[] {{ {string.Join(", ", integrationEventHandler.SendCommands?.Select(c => $"\"{EscapeCSharpString(c)}\"") ?? Array.Empty<string>())} }} }}",
            
            IntegrationEventConverterMetadataAttribute converter =>
                $"new IntegrationEventConverterMetadataAttribute(\"{EscapeCSharpString(converter.DomainEventType)}\", \"{EscapeCSharpString(converter.IntegrationEventType)}\")",
            
            ControllerMethodMetadataAttribute controllerMethod =>
                $"new ControllerMethodMetadataAttribute(\"{EscapeCSharpString(controllerMethod.ControllerType)}\", \"{EscapeCSharpString(controllerMethod.MethodName)}\") {{ CommandTypes = new[] {{ {string.Join(", ", controllerMethod.CommandTypes?.Select(c => $"\"{EscapeCSharpString(c)}\"") ?? Array.Empty<string>())} }} }}",
            
            EndpointMetadataAttribute endpoint =>
                $"new EndpointMetadataAttribute(\"{EscapeCSharpString(endpoint.EndpointType)}\") {{ CommandTypes = new[] {{ {string.Join(", ", endpoint.CommandTypes?.Select(c => $"\"{EscapeCSharpString(c)}\"") ?? Array.Empty<string>())} }} }}",
            
            CommandSenderMethodMetadataAttribute commandSenderMethod =>
                $"new CommandSenderMethodMetadataAttribute(\"{EscapeCSharpString(commandSenderMethod.SenderType)}\", \"{EscapeCSharpString(commandSenderMethod.MethodName)}\") {{ CommandTypes = new[] {{ {string.Join(", ", commandSenderMethod.CommandTypes?.Select(c => $"\"{EscapeCSharpString(c)}\"") ?? Array.Empty<string>())} }} }}",
            
            _ => throw new NotSupportedException($"Unsupported MetadataAttribute type: {attr.GetType().Name}")
        };
    }
    
    /// <summary>
    /// 从程序集中扫描获取CodeFlowAnalysisSnapshot实例列表
    /// </summary>
    /// <param name="assemblies">要扫描的程序集数组</param>
    /// <returns>快照实例列表</returns>
    public static List<CodeFlowAnalysisSnapshot> ScanSnapshotsFromAssemblies(params Assembly[] assemblies)
    {
        var snapshots = new List<CodeFlowAnalysisSnapshot>();
        
        foreach (var assembly in assemblies)
        {
            try
            {
                // 查找所有快照类（在CodeAnalysisSnapshots命名空间下，继承自CodeFlowAnalysisSnapshot）
                var snapshotTypes = assembly.GetTypes()
                    .Where(t => t.Namespace == "CodeAnalysisSnapshots" 
                             && typeof(CodeFlowAnalysisSnapshot).IsAssignableFrom(t)
                             && t.IsClass 
                             && !t.IsAbstract)
                    .ToList();
                
                foreach (var type in snapshotTypes)
                {
                    try
                    {
                        // 创建快照实例（通过无参构造函数）
                        var snapshot = Activator.CreateInstance(type) as CodeFlowAnalysisSnapshot;
                        if (snapshot != null)
                        {
                            snapshots.Add(snapshot);
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.Error.WriteLine($"Error creating snapshot instance for type {type.Name}: {ex.Message}");
                    }
                }
            }
            catch (Exception ex)
            {
                // 记录错误但继续处理其他程序集
                Console.Error.WriteLine($"Error scanning assembly {assembly.FullName}: {ex.Message}");
            }
        }
        
        // 按版本号排序
        return snapshots.OrderBy(s => s.Metadata.Version).ToList();
    }
    
    /// <summary>
    /// 生成快照类名，格式为：版本号_名称（如果提供）
    /// 例如：20250922092235_InitialCreate0922 或 20250922092235
    /// </summary>
    /// <param name="version">版本号（时间戳）</param>
    /// <param name="name">快照名称（可选）</param>
    /// <returns>类名</returns>
    public static string GenerateClassName(string version, string? name = null)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return $"{version}";
        }
        
        // 清理名称，确保是有效的C#标识符
        var sanitizedName = SanitizeIdentifier(name);
        return $"{version}_{sanitizedName}";
    }
    
    /// <summary>
    /// 生成文件名，格式为：版本号_名称.cs（如果提供名称）或 版本号.cs
    /// 例如：20250922092235_InitialCreate0922.cs
    /// </summary>
    /// <param name="version">版本号（时间戳）</param>
    /// <param name="name">快照名称（可选）</param>
    /// <returns>文件名</returns>
    public static string GenerateFileName(string version, string? name = null)
    {
        return $"{GenerateClassName(version, name)}.cs";
    }
    
    /// <summary>
    /// 清理字符串使其成为有效的C#标识符
    /// </summary>
    private static string SanitizeIdentifier(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return "Snapshot";
            
        var sb = new StringBuilder();
        foreach (var c in input)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                sb.Append(c);
            }
        }
        
        var result = sb.ToString();
        
        // 确保不以数字开头
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "S" + result;
        }
        
        return string.IsNullOrWhiteSpace(result) ? "Snapshot" : result;
    }
    
    /// <summary>
    /// 计算分析结果的哈希值
    /// </summary>
    private static string ComputeHash(CodeFlowAnalysisResult analysisResult)
    {
        var sb = new StringBuilder();
        foreach (var node in analysisResult.Nodes.OrderBy(n => n.Id))
        {
            sb.Append($"{node.Id}|{node.Name}|{node.Type}|");
        }
        foreach (var rel in analysisResult.Relationships.OrderBy(r => r.FromNode.Id).ThenBy(r => r.ToNode.Id))
        {
            sb.Append($"{rel.FromNode.Id}->{rel.ToNode.Id}|{rel.Type}|");
        }
        using var sha256 = SHA256.Create();
        var hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }
    
    /// <summary>
    /// 转义C#字符串
    /// </summary>
    private static string EscapeCSharpString(string input)
    {
        if (string.IsNullOrEmpty(input))
            return string.Empty;
            
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
    
    /// <summary>
    /// Runtime snapshot implementation used by helper methods
    /// </summary>
    private class RuntimeSnapshot : CodeFlowAnalysisSnapshot
    {
        public RuntimeSnapshot(SnapshotMetadata metadata, List<MetadataAttribute> metadataAttributes)
        {
            Metadata = metadata;
            MetadataAttributes = metadataAttributes;
        }
    }
}
