using System;
using System.Linq;
using System.Text;

namespace NetCorePal.Extensions.CodeAnalysis.Snapshots;

/// <summary>
/// 生成C#快照代码文件，类似EF Core的迁移快照
/// </summary>
public static class SnapshotCodeGenerator
{
    public static string GenerateSnapshotClass(CodeFlowAnalysisResult analysisResult, SnapshotMetadata metadata)
    {
        var sb = new StringBuilder();
        
        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Snapshot created: {metadata.Timestamp:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"// Description: {EscapeCSharpString(metadata.Description)}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis;");
        sb.AppendLine("using NetCorePal.Extensions.CodeAnalysis.Snapshots;");
        sb.AppendLine();
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        
        // Namespace
        sb.AppendLine("namespace CodeAnalysisSnapshots");
        sb.AppendLine("{");
        
        // Class declaration
        var className = $"Snapshot_{metadata.Version}";
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");
        
        // BuildSnapshot method
        sb.AppendLine("        public static CodeFlowAnalysisSnapshot BuildSnapshot()");
        sb.AppendLine("        {");
        sb.AppendLine("            var nodes = new List<Node>");
        sb.AppendLine("            {");
        
        // Generate nodes
        foreach (var node in analysisResult.Nodes)
        {
            sb.AppendLine("                new Node");
            sb.AppendLine("                {");
            sb.AppendLine($"                    Id = \"{EscapeCSharpString(node.Id)}\",");
            sb.AppendLine($"                    Name = \"{EscapeCSharpString(node.Name)}\",");
            sb.AppendLine($"                    FullName = \"{EscapeCSharpString(node.FullName)}\",");
            sb.AppendLine($"                    Type = NodeType.{node.Type}");
            sb.AppendLine("                },");
        }
        
        sb.AppendLine("            };");
        sb.AppendLine();
        sb.AppendLine("            var relationships = new List<Relationship>");
        sb.AppendLine("            {");
        
        // Generate relationships (need to reference nodes from the list)
        var nodeDict = analysisResult.Nodes.Select((n, i) => new { n.Id, Index = i }).ToDictionary(x => x.Id, x => x.Index);
        
        foreach (var rel in analysisResult.Relationships)
        {
            var fromIndex = nodeDict.TryGetValue(rel.FromNode.Id, out var fi) ? fi : -1;
            var toIndex = nodeDict.TryGetValue(rel.ToNode.Id, out var ti) ? ti : -1;
            
            if (fromIndex >= 0 && toIndex >= 0)
            {
                sb.AppendLine($"                new Relationship(nodes[{fromIndex}], nodes[{toIndex}], RelationshipType.{rel.Type}),");
            }
        }
        
        sb.AppendLine("            };");
        sb.AppendLine();
        
        // Create and return snapshot
        sb.AppendLine("            return new CodeFlowAnalysisSnapshot");
        sb.AppendLine("            {");
        sb.AppendLine("                Metadata = new SnapshotMetadata");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Version = \"{metadata.Version}\",");
        sb.AppendLine($"                    Timestamp = DateTime.Parse(\"{metadata.Timestamp:yyyy-MM-dd HH:mm:ss}\"),");
        sb.AppendLine($"                    Description = \"{EscapeCSharpString(metadata.Description)}\",");
        sb.AppendLine($"                    Hash = \"{metadata.Hash}\",");
        sb.AppendLine($"                    NodeCount = {metadata.NodeCount},");
        sb.AppendLine($"                    RelationshipCount = {metadata.RelationshipCount}");
        sb.AppendLine("                },");
        sb.AppendLine("                AnalysisResult = new CodeFlowAnalysisResult");
        sb.AppendLine("                {");
        sb.AppendLine("                    Nodes = nodes,");
        sb.AppendLine("                    Relationships = relationships");
        sb.AppendLine("                }");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    private static string EscapeCSharpString(string input)
    {
        if (string.IsNullOrEmpty(input))
            return string.Empty;
            
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
