using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using NetCorePal.Extensions.CodeAnalysis;
using NetCorePal.Extensions.CodeAnalysis.Attributes;
using NetCorePal.Extensions.CodeAnalysis.Snapshots;
using Xunit;

namespace NetCorePal.Extensions.CodeAnalysis.Tools.UnitTests;

public class CodeFlowAnalysisSnapshotHelperTests
{
    [Fact]
    public void CreateSnapshot_ShouldCreateValidSnapshot()
    {
        // Arrange - Create test metadata attributes
        var metadataAttributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };
        var description = "Test snapshot";
        var version = "20260116120000";

        // Act
        var snapshot = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, description, version);

        // Assert
        Assert.NotNull(snapshot);
        Assert.NotNull(snapshot.Metadata);
        Assert.Equal(version, snapshot.Metadata.Version);
        Assert.Equal(description, snapshot.Metadata.Description);
        Assert.NotNull(snapshot.Metadata.Hash);
        Assert.NotEmpty(snapshot.Metadata.Hash);
        
        // Verify we can get the analysis result from MetadataAttributes
        var result = snapshot.GetAnalysisResult();
        Assert.NotNull(result);
        Assert.NotNull(result.Nodes);
        Assert.NotNull(result.Relationships);
    }

    [Fact]
    public void CreateSnapshot_WithoutVersion_ShouldUseTimestamp()
    {
        // Arrange - Create test metadata attributes
        var metadataAttributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };
        var description = "Test snapshot";

        // Act
        var snapshot = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, description);

        // Assert
        Assert.NotNull(snapshot);
        Assert.NotNull(snapshot.Metadata);
        Assert.NotNull(snapshot.Metadata.Version);
        Assert.NotEmpty(snapshot.Metadata.Version);
        Assert.Equal(14, snapshot.Metadata.Version.Length); // yyyyMMddHHmmss format
    }

    [Fact]
    public void GenerateSnapshotCode_ShouldGenerateValidCSharpCode()
    {
        // Arrange
        var analysisResult = CreateTestAnalysisResult();
        var metadata = new SnapshotMetadata
        {
            Version = "20260116120000",
            Timestamp = DateTime.Parse("2026-01-16 12:00:00"),
            Description = "Test snapshot",
            Hash = "abc123",
            NodeCount = 2,
            RelationshipCount = 1
        };

        // Act
        // Create simple metadata attributes for testing
        var attributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };
        var code = CodeFlowAnalysisSnapshotHelper.GenerateSnapshotCode(attributes, metadata, null);

        // Assert
        Assert.NotNull(code);
        Assert.Contains("// <auto-generated />", code);
        Assert.Contains("public partial class 20260116120000 : CodeFlowAnalysisSnapshot", code);
        Assert.Contains("namespace CodeAnalysisSnapshots", code);
        Assert.Contains("Metadata = new SnapshotMetadata", code);
        Assert.Contains("MetadataAttributes = new MetadataAttribute[]", code); // Changed from AnalysisResult
        Assert.Contains("Version = \"20260116120000\"", code);
        Assert.Contains("Description = \"Test snapshot\"", code);
    }

    [Fact]
    public void GenerateSnapshotCode_WithName_ShouldIncludeNameInClassName()
    {
        // Arrange
        var analysisResult = CreateTestAnalysisResult();
        var metadata = new SnapshotMetadata
        {
            Version = "20260116120000",
            Timestamp = DateTime.Now,
            Description = "Test",
            Hash = "abc",
            NodeCount = 2,
            RelationshipCount = 1
        };

        // Act
        // Create simple metadata attributes for testing
        var attributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };
        var code = CodeFlowAnalysisSnapshotHelper.GenerateSnapshotCode(attributes, metadata, "InitialCreate");

        // Assert
        Assert.Contains("public partial class 20260116120000_InitialCreate : CodeFlowAnalysisSnapshot", code);
    }

    [Fact]
    public void GenerateSnapshotCode_FromSnapshot_ShouldGenerateValidCode()
    {
        // Arrange - Create test metadata attributes
        var metadataAttributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };
        var snapshot = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, "Test", "20260116120000");

        // Act
        var code = CodeFlowAnalysisSnapshotHelper.GenerateSnapshotCode(snapshot, "TestSnapshot");

        // Assert
        Assert.NotNull(code);
        Assert.Contains("public partial class 20260116120000_TestSnapshot : CodeFlowAnalysisSnapshot", code);
    }

    [Fact]
    public void GenerateClassName_WithoutName_ShouldReturnVersionOnly()
    {
        // Arrange
        var version = "20260116120000";

        // Act
        var className = CodeFlowAnalysisSnapshotHelper.GenerateClassName(version, null);

        // Assert
        Assert.Equal("20260116120000", className);
    }

    [Fact]
    public void GenerateClassName_WithName_ShouldReturnVersionAndName()
    {
        // Arrange
        var version = "20260116120000";
        var name = "InitialCreate";

        // Act
        var className = CodeFlowAnalysisSnapshotHelper.GenerateClassName(version, name);

        // Assert
        Assert.Equal("20260116120000_InitialCreate", className);
    }

    [Fact]
    public void GenerateClassName_WithSpecialCharacters_ShouldSanitize()
    {
        // Arrange
        var version = "20260116120000";
        var name = "Initial-Create@2024!";

        // Act
        var className = CodeFlowAnalysisSnapshotHelper.GenerateClassName(version, name);

        // Assert
        Assert.Equal("20260116120000_InitialCreate2024", className);
        Assert.DoesNotContain("-", className);
        Assert.DoesNotContain("@", className);
        Assert.DoesNotContain("!", className);
    }

    [Fact]
    public void GenerateFileName_WithoutName_ShouldReturnVersionDotCs()
    {
        // Arrange
        var version = "20260116120000";

        // Act
        var fileName = CodeFlowAnalysisSnapshotHelper.GenerateFileName(version, null);

        // Assert
        Assert.Equal("20260116120000.cs", fileName);
    }

    [Fact]
    public void GenerateFileName_WithName_ShouldReturnVersionAndNameDotCs()
    {
        // Arrange
        var version = "20260116120000";
        var name = "InitialCreate";

        // Act
        var fileName = CodeFlowAnalysisSnapshotHelper.GenerateFileName(version, name);

        // Assert
        Assert.Equal("20260116120000_InitialCreate.cs", fileName);
    }

    [Fact]
    public void ScanSnapshotsFromAssemblies_WithNoSnapshots_ShouldReturnEmptyList()
    {
        // Arrange
        var assembly = typeof(CodeFlowAnalysisSnapshotHelperTests).Assembly;

        // Act
        var snapshots = CodeFlowAnalysisSnapshotHelper.ScanSnapshotsFromAssemblies(assembly);

        // Assert
        Assert.NotNull(snapshots);
        Assert.Empty(snapshots);
    }

    [Fact]
    public void CreateSnapshot_WithEmptyMetadataAttributes_ShouldHaveZeroCounts()
    {
        // Arrange - Create empty metadata attributes array
        var metadataAttributes = Array.Empty<MetadataAttribute>();

        // Act
        var snapshot = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, "Empty snapshot");

        // Assert
        Assert.Equal(0, snapshot.Metadata.NodeCount);
        Assert.Equal(0, snapshot.Metadata.RelationshipCount);
    }

    [Fact]
    public void CreateSnapshot_WithSameData_ShouldGenerateSameHash()
    {
        // Arrange - Create test metadata attributes
        var metadataAttributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"TestMethod"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {"TestEvent"}, new string[] {})
        };

        // Act
        var snapshot1 = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, "Test 1", "v1");
        var snapshot2 = CodeFlowAnalysisSnapshotHelper.CreateSnapshot(metadataAttributes, "Test 2", "v2");

        // Assert
        Assert.Equal(snapshot1.Metadata.Hash, snapshot2.Metadata.Hash);
    }

    [Fact]
    public void GenerateSnapshotCode_ShouldEscapeSpecialCharacters()
    {
        // Arrange
        var nodes = new List<Node>
        {
            new Node { Id = "node1", Name = "Test\"Quote", FullName = "Test\\Backslash", Type = NodeType.Aggregate }
        };
        var analysisResult = new CodeFlowAnalysisResult { Nodes = nodes, Relationships = new List<Relationship>() };
        var metadata = new SnapshotMetadata
        {
            Version = "20260116120000",
            Timestamp = DateTime.Now,
            Description = "Test with \"quotes\" and \\backslashes\\",
            Hash = "abc",
            NodeCount = 1,
            RelationshipCount = 0
        };

        // Act
        // Create simple metadata attributes for testing with special characters
        var attributes = new MetadataAttribute[]
        {
            new EntityMetadataAttribute("Test\"Quote", true, new string[] {}, new string[] {"Test\\Backslash"}),
            new EntityMethodMetadataAttribute("TestEntity", "TestMethod", new string[] {}, new string[] {})
        };
        var code = CodeFlowAnalysisSnapshotHelper.GenerateSnapshotCode(attributes, metadata, null);

        // Assert
        Assert.Contains("Test\\\"Quote", code); // Escaped quote
        Assert.Contains("Test\\\\Backslash", code); // Escaped backslash
        Assert.Contains("Test with \\\"quotes\\\" and \\\\backslashes\\\\", code); // Escaped in description
    }

    [Fact]
    public void GenerateSnapshotCode_WithDuplicateNodeIds_ShouldNotThrowException()
    {
        // Arrange - Create nodes with duplicate IDs (simulating the error scenario)
        var node1 = new Node { Id = "duplicateId", Name = "Node1", FullName = "Test.Node1", Type = NodeType.Aggregate };
        var node2 = new Node { Id = "duplicateId", Name = "Node2", FullName = "Test.Node2", Type = NodeType.EntityMethod };
        var node3 = new Node { Id = "uniqueId", Name = "Node3", FullName = "Test.Node3", Type = NodeType.EntityMethod };
        
        var rel1 = new Relationship(node1, node3, RelationshipType.CommandToAggregate);
        var rel2 = new Relationship(node2, node3, RelationshipType.CommandToAggregate);

        var analysisResult = new CodeFlowAnalysisResult
        {
            Nodes = new List<Node> { node1, node2, node3 },
            Relationships = new List<Relationship> { rel1, rel2 }
        };

        var metadata = new SnapshotMetadata
        {
            Version = "20260116120000",
            Timestamp = DateTime.Now,
            Description = "Test with duplicate node IDs",
            Hash = "test123",
            NodeCount = 3,
            RelationshipCount = 2
        };

        // Act - Should not throw "An item with the same key has already been added" exception
        var exception = Record.Exception(() =>
        {
            // Create metadata attributes with duplicate node IDs (same entity method multiple times)
            var attributes = new MetadataAttribute[]
            {
                new EntityMetadataAttribute("TestEntity", true, new string[] {}, new string[] {"DuplicateMethod"}),
                new EntityMethodMetadataAttribute("TestEntity", "DuplicateMethod", new string[] {"Event1"}, new string[] {}),
                new EntityMethodMetadataAttribute("TestEntity", "DuplicateMethod", new string[] {"Event2"}, new string[] {}) // Duplicate
            };
            var code = CodeFlowAnalysisSnapshotHelper.GenerateSnapshotCode(attributes, metadata, "TestSnapshot");
            Assert.NotNull(code);
            Assert.Contains("public partial class", code);
            Assert.Contains("TestSnapshot", code);
        });

        // Assert
        Assert.Null(exception); // No exception should be thrown
    }

    // Helper method to create test analysis result
    private static CodeFlowAnalysisResult CreateTestAnalysisResult()
    {
        var node1 = new Node { Id = "node1", Name = "TestNode1", FullName = "Test.Node1", Type = NodeType.Aggregate };
        var node2 = new Node { Id = "node2", Name = "TestNode2", FullName = "Test.Node2", Type = NodeType.EntityMethod };
        var rel = new Relationship(node1, node2, RelationshipType.CommandToAggregate);

        return new CodeFlowAnalysisResult
        {
            Nodes = new List<Node> { node1, node2 },
            Relationships = new List<Relationship> { rel }
        };
    }
}
